### ISSUE TITLE
Remove tilde (~) for "people" pages if they are always put under a fixed path (/people/)

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/website-site-ng#62] opened 2017-02-21 21:50 UTC

**Comment by MingcongBai** [comment] 2017-02-21 21:55
Closing. Voted by design.

**Closed by MingcongBai** 2017-02-21 21:55 UTC

**Comment by gumblex** [comment] 2017-02-22 00:53
Make a 301?

**Comment by Artoria2e5** [comment] 2017-02-22 04:16
The awkward point about `people/~` is that `^~` tends to be something that's concealed (e.g. not indexed by many indexing modules), and you are effectively akarin-izing a whole directory. Makes no sense, I mean.

**Comment by Artoria2e5** [comment] 2017-02-22 04:17
(A worse part in the current people system is that it gives not a directory, but a single pig-framed webpage for users to use. Where is the "home" implied by the tilde?)
